-- PROCESSO DE CONSTRUÇÃO DO DDL DO CARDÁPIO ELETRÔNICO
-- 1ª REGRA - COMEÇAR A CONSTRUÇÃO DAS TABELAS QUE NÃO POSSUEM NENHUMA FK

CREATE DATABASE CARDAPIO_ELETRONICO;
USE CARDAPIO_ELETRONICO;

CREATE TABLE CLIENTES (
	ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(100),
    CPF VARCHAR(11),
    NR_CELULAR VARCHAR(15),
    EMAIL VARCHAR(150)
);

CREATE TABLE CATEGORIAS(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20),
    URL_IMAGEM VARCHAR(255)
);

CREATE TABLE PRODUTOS (
	ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100),
    DESCRICAO VARCHAR(255),
    IMAGEM VARCHAR(255),
    VALOR DECIMAL(5, 2),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE CONTA (
	ID_CONTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DATA_HORA_PAGAMENTO DATETIME,
    VALOR_TOTAL DECIMAL(10,2),
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PEDIDOS (
	ID_PEDIDO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    ID_CONTA INT NOT NULL,
    QUANTIDADE INT,
    PRECO_TOTAL DECIMAL(10,2),
    CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO),
    CONSTRAINT FK_PEDIDO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA (ID_CONTA)
);

