CREATE DATABASE DHtube;
USE DHtube;

CREATE TABLE AVATAR (
	ID_AVATAR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45),
    URL_IMAGEM VARCHAR(100)
);

CREATE TABLE PAIS (
	ID_PAIS INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE USUARIOS (
	ID_USUARIOS INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PAIS INT(11) NOT NULL,
    ID_AVATAR INT(11) NOT NULL,
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    SENHA VARCHAR(45),
    DATA_NASCIMENTO DATETIME,
    CEP VARCHAR(45),
    CONSTRAINT FK_USUARIOS_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS),
    CONSTRAINT FK_USUARIOS_AVATAR FOREIGN KEY (ID_AVATAR) REFERENCES AVATAR (ID_AVATAR)
);

CREATE TABLE PLAYLIST (
	ID_PLAYLIST INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_USUARIOS INT(11) NOT NULL,
    NOME VARCHAR(45),
    DATA_CRIACAO DATETIME,
    PRIVADO SMALLINT(6),
    CONSTRAINT FK_PLAYLIST_USUARIOS FOREIGN KEY (ID_USUARIOS) REFERENCES USUARIOS (ID_USUARIOS)
);

CREATE TABLE CANAL (
	ID_CANAL INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_USUARIOS INT(11) NOT NULL,
    NOME VARCHAR(45),
    DESCRICAO TEXT,
    DATA_CRIACAO DATETIME,
    CONSTRAINT FK_CANAL_USUARIOS FOREIGN KEY (ID_USUARIOS) REFERENCES USUARIOS (ID_USUARIOS)
);

CREATE TABLE VIDEOS (
	ID_VIDEOS INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_USUARIOS INT(11) NOT NULL,
    TITULO VARCHAR(100),
    DESCRICAO TEXT,
    TAMANHO DOUBLE,
    NOME_ARQUIVO VARCHAR(100),
    DURACAO DOUBLE,
    IMAGEM VARCHAR(100),
    QTD_REPRODUCOES INT(11),
    QTD_LIKES INT(11),
    QTD_DISLIKES INT(11),
    PRIVADO SMALLINT(6),
    DATA_PUBLICACAO DATETIME,
    CONSTRAINT FK_VIDEOS_USUARIOS FOREIGN KEY (ID_USUARIOS) REFERENCES USUARIOS (ID_USUARIOS)
);

CREATE TABLE PLAYLIST_VIDEOS (
	ID_PLAYLIST_VIDEOS INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_VIDEOS INT(11) NOT NULL,
    ID_PLAYLIST INT(11) NOT NULL,
    CONSTRAINT FK_PLAYLIST_VIDEOS_VIDEOS FOREIGN KEY (ID_VIDEOS) REFERENCES VIDEOS (ID_VIDEOS),
    CONSTRAINT FK_PLAYLIST_VIDEOS_PLAYLIST FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST (ID_PLAYLIST)
);

-- HELTER EMANOEL, LUCAS SOARES, PABLO OLIVEIRA - SALA 08