-- CONJUNTO DE INSTRUÇÕES DDL
-- CREATE DATABASE - INSTRUÇÃO RESPONSÁVEL POR CRIAR UM BANCO DE DADOS
-- SINTAXE = INSTRUÇÃO | OBJETO | PARÂMETROS/ATRIBUTOS
CREATE DATABASE AULA8;
USE AULA8;

-- CREATE TABLE - INSTRUÇÃO RESPONSÁVEL POR CRIAR A ESTRUTURA DE UMA TABELA
CREATE TABLE PACIENTE (
	ID_PACIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NR_CARTEIRINHA INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    SOBRENOME VARCHAR(150)
);

-- DROP TABLE - INSTRUÇÃO RESPONSÁVEL POR ELIMINAR UMA TABELA
-- DROP TABLE PACIENTE;

-- ALTER TABLE - INSTRUÇÃO RESPONSÁVEL POR ALTERAR A ESTRUTURA DE UMA TABELA
ALTER TABLE PACIENTE MODIFY NOME VARCHAR(200);

-- DROP DATABASE - INSTRUÇÃO RESPONSÁVEL POR ELIMINAR UM BANCO DE DADOS INTEIRO
-- DROP DATABASE AULA8;